sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck:latest

script:
  - docker run --volume $PWD:/scripts koalaman/shellcheck /scripts/nvi /scripts/test-nvi
  - ./test-nvi
